/* specifies the layout of the ISR vector table */

#include "core.h"
#include "kernel/panic.h"
#include "inc/interrupt_def.h"

extern void _estack(void); // linker-supplied address; this type because of the vector table's type
// TODO no, the above isn't nice -- the conversion should be more explicit

extern void _start(void) __attribute__((noreturn)); // defined in main.c

// create default implementations for all system interrupt handlers -- will cause a panic if the
// exception occurs unless they are overriden
ISR_UNEXPECTED( INT_NMI       )
ISR_UNEXPECTED( INT_HARDFAULT )
ISR_UNEXPECTED( INT_SVCALL    )
ISR_UNEXPECTED( INT_PENDSV    )
ISR_UNEXPECTED( INT_SYSTICK   )

// create empty default implementations for all hardware interrupt handlers
// TODO either remove the need to do this explicitly, or generate with a preprocessor for loop
ISR_NULL( INT_WWDG                )
ISR_NULL( INT_PVD_VDDIO2          )
ISR_NULL( INT_RTC                 )
ISR_NULL( INT_FLASH               )
ISR_NULL( INT_RCC_CRS             )
ISR_NULL( INT_EXTI0_1             )
ISR_NULL( INT_EXTI2_3             )
ISR_NULL( INT_EXTI4_15            )
ISR_NULL( INT_TSC                 )
ISR_NULL( INT_DMA_CH1             )
ISR_NULL( INT_DMA_CH2_3           )
ISR_NULL( INT_DMA_CH4_5_6_7       )
ISR_NULL( INT_ADC_COMP            )
ISR_NULL( INT_TIM1_BRK_UP_TRG_COM )
ISR_NULL( INT_TIM1_CC             )
ISR_NULL( INT_TIM2                )
ISR_NULL( INT_TIM3                )
ISR_NULL( INT_TIM6_DAC            )
ISR_NULL( INT_TIM7                )
ISR_NULL( INT_TIM14               )
ISR_NULL( INT_TIM15               )
ISR_NULL( INT_TIM16               )
ISR_NULL( INT_TIM17               )
ISR_NULL( INT_I2C1                )
ISR_NULL( INT_I2C2                )
ISR_NULL( INT_SPI1                )
ISR_NULL( INT_SPI2                )
ISR_NULL( INT_USART1              )
ISR_NULL( INT_USART2              )
ISR_NULL( INT_USART3_4            )
ISR_NULL( INT_CEC_CAN             )
ISR_NULL( INT_USB                 )

// the linker script puts .isr_vector at 0x0
void (*isr_vector[])(void) __attribute__((section(".isr_vector"))) = {
    _estack ,// stack top
    _start  ,// entry point
    // system interrupts
    INTFN(INT_NMI),
    INTFN(INT_HARDFAULT),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    INTFN(INT_SVCALL),
    NULL,
    NULL,
    INTFN(INT_PENDSV),
    INTFN(INT_SYSTICK),
    // hardware interrupts
    // TODO the following are actually just consecutive numbers, maybe they should be generated by a
    // preprocessor for loop if I find the courage
    INTFN(INT_WWDG),
    INTFN(INT_PVD_VDDIO2),
    INTFN(INT_RTC),
    INTFN(INT_FLASH),
    INTFN(INT_RCC_CRS),
    INTFN(INT_EXTI0_1),
    INTFN(INT_EXTI2_3),
    INTFN(INT_EXTI4_15),
    INTFN(INT_TSC),
    INTFN(INT_DMA_CH1),
    INTFN(INT_DMA_CH2_3),
    INTFN(INT_DMA_CH4_5_6_7),
    INTFN(INT_ADC_COMP),
    INTFN(INT_TIM1_BRK_UP_TRG_COM),
    INTFN(INT_TIM1_CC),
    INTFN(INT_TIM2),
    INTFN(INT_TIM3),
    INTFN(INT_TIM6_DAC),
    INTFN(INT_TIM7),
    INTFN(INT_TIM14),
    INTFN(INT_TIM15),
    INTFN(INT_TIM16),
    INTFN(INT_TIM17),
    INTFN(INT_I2C1),
    INTFN(INT_I2C2),
    INTFN(INT_SPI1),
    INTFN(INT_SPI2),
    INTFN(INT_USART1),
    INTFN(INT_USART2),
    INTFN(INT_USART3_4),
    INTFN(INT_CEC_CAN),
    INTFN(INT_USB),
};
