/* defines Cortex M0 system interrupt numbers */

#ifndef MCUS_CORTEXM0_COMMON_SYSTEM_INTERRUPTS_H
#define MCUS_CORTEXM0_COMMON_SYSTEM_INTERRUPTS_H


// note: must not clash with any hardware interrupt numbers
// therefore here the constant 0x1000 is added
#define INT_NMI        0x1008 // non-maskable interrupt
#define INT_HARDFAULT  0x100c // hardfault exception
#define INT_SVCALL     0x102c // supervisor call (software interrupt) -- used for system calls
#define INT_PENDSV     0x1038 // request for service (asynchronous => use for "scheduling" stuff)
#define INT_SYSTICK    0x103c //system tick (generated by the configurable systick timer)

#define _SYSTEM_INTERRUPTS_ADDED  0x1000 // used internally bu the interrupt controller driver


#endif
