/* defines interrupt handlers + stuffs them at the correct address */
// TODO this whole thing needs to be re-thought

#include "interrupts.h"

extern void _estack(void); // linker-supplied address; this type because of the vector table's type
// TODO no, the above isn't nice -- the conversion should be even more explicit

extern void _start(void) __attribute__((noreturn)); // defined in main.c

// so that the CPU state can be examined after an unexpected interrupt
void default_exception_handler(void) { while (1) ; }
void default_interrupt_handler(void) { while (1) ; }

// this should be written using my macros
void nmi_handler      (void) __attribute__((interrupt, weak, alias("default_exception_handler")));
void hardfault_handler(void) __attribute__((interrupt, weak, alias("default_exception_handler")));
void SVcall_handler   (void) __attribute__((interrupt, weak, alias("default_interrupt_handler")));
void pendSV_handler   (void) __attribute__((interrupt, weak, alias("default_interrupt_handler")));
void systick_handler  (void) __attribute__((interrupt, weak, alias("default_interrupt_handler")));

// the linker script puts .isr_vector at 0x0
void (*isr_vector[])(void) __attribute__((section(".isr_vector"))) = {
    _estack           ,// stack top
    _start            ,// (01) entry point
    nmi_handler       ,// (02) NMI handler
    hardfault_handler ,// (03) hardfault handler
    NULL              ,// (04) [reserved]
    NULL              ,// (05) [reserved]
    NULL              ,// (06) [reserved]
    NULL              ,// (07) [reserved]
    NULL              ,// (08) [reserved]
    NULL              ,// (09) [reserved]
    NULL              ,// (10) [reserved]
    SVcall_handler    ,// (11) supervisor call (software interrupt) -- used for system calls
    NULL              ,// (12) [reserved]
    NULL              ,// (13) [reserved]
    pendSV_handler    ,// (14) request for service (asynchronous => use for "scheduling" stuff)
    systick_handler   ,// (15) system tick (generated by the configurable systick timer)
    // IRQs go here
};
