/* defines Cortex M4 system interrupt numbers */

#ifndef MCUS_CORTEXM4_COMMON_SYSTEM_INTERRUPTS_H
#define MCUS_CORTEXM4_COMMON_SYSTEM_INTERRUPTS_H


/*
 * Those interrupts are numbered according to their exception numbers, see
 * http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0553a/BABIFJFG.html
 */

#define INT_RESET       1   // system reset exception
#define INT_NMI         2   // non-maskable interrupt
#define INT_HARDFAULT   3   // hardfault exception
#define INT_MEMMANAGE   4   // memory management fault
#define INT_BUSFAULT    5   // pre-fetch fault, memory access fault
#define INT_USAGEFAULT  6   // undefined instruction or illegal state
#define INT_SVCALL      11  // supervisor call (software interrupt) -- used for system calls
#define INT_PENDSV      14  // request for service (asynchronous => use for "scheduling" stuff)
#define INT_SYSTICK     15  // system tick (generated by the configurable systick timer)

#define _IRQ_OFFSET     16  // used internally by the interrupt controller driver
#define _EXN_MAX        255 // maximum Cortex M4 exception number


#endif
